#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

export HOME=/var/apps/cpolar/etc
export PATH=/var/apps/cpolar/target/server:$PATH

CMD="cpolar start-all -dashboard=on -daemon=on -config=/var/apps/cpolar/etc/cpolar.yml "
# CMD=""

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."

    # run cmd to start process
    ${CMD} >> ${LOG_FILE} 2>&1 &

    # write pid to pidfile
    echo $! > ${PID_FILE}

    sleep 1

    if pidof cpolar >/dev/null; then
        log_msg "Started successfully"
        return 0
    else
        log_msg "Start failed"
        return 1
    fi
}

stop_process() {
    log_msg "Stopping process ..."

    pids=$(pidof cpolar)

    if [ -z "$pids" ]; then
        log_msg "cpolar not running"
        rm -f "${PID_FILE}"
        return 0
    fi

    log_msg "pids=$pids"

    kill -TERM $pids >> ${LOG_FILE} 2>&1

    local count=0
    while pidof cpolar >/dev/null && [ $count -lt 10 ]; do
        sleep 1
        count=$((count + 1))
        log_msg "waiting process terminate... (${count}s/10s)"
    done

    if pidof cpolar >/dev/null; then
        log_msg "force kill"
        kill -KILL $(pidof cpolar) >> ${LOG_FILE} 2>&1
    fi

    rm -f "${PID_FILE}"
    log_msg "Stopped"
}

status() {
    if pidof cpolar >/dev/null; then
        return 0
    else
        return 1
    fi
}

case $1 in
start)
    start_process
    ;;
stop)
    stop_process
    ;;
status)
    if status; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac