#!/bin/bash
LOG_FILE="${TRIM_PKGVAR}/info.log"
INSTALL_TARGETDIR="/var/apps/ddnsto/target/server"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

#获取处理器架构
ARCH=""
case "${TRIM_SYS_ARCH}" in
    x86_64|x86)
        ARCH="amd64"
        ;;
    aarch64|arm)
        ARCH="arm64"
        ;;
    *)
        log_msg "不支持的架构: $TRIM_SYS_ARCH"
        exit 1
        ;;
esac

DICT_URL="https://fw.koolcenter.com/binary/ddnsto/linux/ddnsto.$ARCH"
log_msg "准备下载: ${DICT_URL}"

mkdir -p "${INSTALL_TARGETDIR}" && cd ${INSTALL_TARGETDIR}
wget -c "$DICT_URL" --show-progress || {
    log_msg "下载 ddnsto 失败"
    exit 1
}
log_msg "下载完成: ${INSTALL_TARGETDIR}/$DICT_FILE"

mv "ddnsto.${ARCH}" "ddnsto"
chmod +x "ddnsto"
log_msg "安装完成: ${INSTALL_TARGETDIR}/ddnsto"

exit 0